import React from 'react'
import { Header, Modal } from 'semantic-ui-react'
import boopModal from '../images/boopModal.jpg'

function AboutModal(props) {

   const style = {
      backgroundImage: `url(${boopModal})`,
      backgroundPosition: 'center',
      backgroundSize: 'cover',
      backgroundRepeat: 'no-repeat',
      height: "100%",
      width: "100%"
    }


  return (
    <>

    <Header textAlign="center" as='h2'>What is Barks and Rec?</Header>
    
      <Modal.Description>
        <div style={ {padding: "10px 25px", textAlign: "center", fontSize: "medium"} }>
      <p>
      Barks and Rec is a role-based user app that facilitates communication about the adoption process between an animal rescue or shelter and its potential adopters. 
      <br></br>
      <br></br>
      Adopter users can submit an application to adopt, and learn more about the dogs that are up for adoption. Adopters can favorite dogs they have an eye on. 
      <br></br>
      <br></br>
      The rescue admin users can add, edit, and view dog profiles. Admins can view registered adopters, and review their applications for adoption approval based on a task list generated by each application submission. </p></div>
      </Modal.Description>
    </>
  )
}

export default AboutModal