const SET_ADOPTER_USER = "SET_ADOPTER_USER"
const SET_ADMIN_USER = "SET_ADMIN_USER"
const LOGOUT = "LOGOUT"
const FETCH_ALL_DOGS = "FETCH_ALL_DOGS"
const FETCH_ALL_ADOPTERS = "FETCH_ALL_ADOPTERS"
const FETCH_ALL_APPLICATIONS = "FETCH_ALL_APPLICATIONS"
const FETCH_ALL_TASKS = "FETCH_ALL_TASKS"
const FETCH_ALL_FAVORITES = "FETCH_ALL_FAVORITES"
const ADD_FAVORITE = "ADD_FAVORITE"
const REMOVE_FAVORITE = "REMOVE_FAVORITE"
const SUBMIT_APPLICATION = "SUBMIT_APPLICATION"
const NEW_TASK = "NEW_TASK"
const FINAL_APPROVAL_TASK = "FINAL_APPROVAL_TASK"
const ADD_DOG = "ADD_DOG"
const UPDATE_DOG = "UPDATE_DOG"
const REMOVE_NOTIFICATION = "REMOVE_NOTIFICATION"
const ADD_NOTIFICATION = "ADD_NOTIFICATION"
const ADD_FINAL_NOTIFICATION = "ADD_FINAL_NOTIFICATION"


export {
  SET_ADOPTER_USER,
  SET_ADMIN_USER, 
  LOGOUT, 
  FETCH_ALL_DOGS, 
  FETCH_ALL_ADOPTERS,
  FETCH_ALL_APPLICATIONS, 
  ADD_FAVORITE, 
  REMOVE_FAVORITE, 
  SUBMIT_APPLICATION,
  FETCH_ALL_TASKS,
  FETCH_ALL_FAVORITES,
  NEW_TASK,
  FINAL_APPROVAL_TASK,
  ADD_DOG,
  UPDATE_DOG, 
  REMOVE_NOTIFICATION,
  ADD_NOTIFICATION,
  ADD_FINAL_NOTIFICATION
}