const SET_ADOPTER_USER = "SET_ADOPTER_USER"
const SET_ADMIN_USER = "SET_ADMIN_USER"
const LOGOUT = "LOGOUT"
const FETCH_ALL_DOGS = "FETCH_ALL_DOGS"
const FETCH_ALL_ADOPTERS = "FETCH_ALL_ADOPTERS"
const FETCH_ALL_APPLICATIONS = "FETCH_ALL_APPLICATIONS"
const FETCH_ALL_TASKS = "FETCH_ALL_TASKS"
const ADD_FAVORITE = "ADD_FAVORITE"
const REMOVE_FAVORITE = "REMOVE_FAVORITE"
const SUBMIT_APPLICATION = "SUBMIT_APPLICATION"


export {
  SET_ADOPTER_USER,
  SET_ADMIN_USER, 
  LOGOUT, 
  FETCH_ALL_DOGS, 
  FETCH_ALL_ADOPTERS,
  FETCH_ALL_APPLICATIONS, 
  ADD_FAVORITE, 
  REMOVE_FAVORITE, 
  SUBMIT_APPLICATION,
  FETCH_ALL_TASKS
}