const SET_ADOPTER_USER = "SET_ADOPTER_USER"
const SET_ADMIN_USER = "SET_ADMIN_USER"
const LOGOUT = "LOGOUT"
const FETCH_ALL_DOGS = "FETCH_ALL_DOGS"
const FETCH_ALL_ADOPTERS = "FETCH_ALL_ADOPTERS"
const FETCH_ALL_APPLICATIONS = "FETCH_ALL_APPLICATIONS"


export {
  SET_ADOPTER_USER,
  SET_ADMIN_USER, 
  LOGOUT, 
  FETCH_ALL_DOGS, 
  FETCH_ALL_ADOPTERS,
  FETCH_ALL_APPLICATIONS
}